Implementation of SCIM API, fixing pom headers and fixing store lookups
wso2/carbon-auth pull request #27
Opened 2017-10-23 07:53 UTC by Niveathika92

2017-10-23 08:37 UTC, uvindra requested changes

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +    private static final Log LOG = LogFactory.getLog(GroupsApiServiceImpl.class);
Wrong variable naming convention, should be "log"

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/GroupsApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +    private static final Log LOG = LogFactory.getLog(GroupsApiServiceImpl.class);
Wrong variable naming convention, should be "log"

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/MeApiServiceImpl.java
> +            LOG.error("User id not found in the request.");
Execution of this branch of code will lead to a null being returned from the function. But it seems that this function is being used without a null check! Ideally an error should be retuned to the end user stating that a mandatory field "authzUser" has not been sent

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/impl/UsersApiServiceImpl.java
> +            LOG.error("Error in initializing the CarbonAuthUserManager.");
Exception has not been logged. Need to log exception as follows,

log.error("Message", e);

2017-10-23 08:37 UTC, uvindra commented on components/auth/org.wso2.carbon.auth.user.store/src/main/java/org/wso2/carbon/auth/user/store/connector/UserStoreConnectorFactory.java
> +                System.out.print(e);
Avoid system.out's. Use logging

2018-01-08 05:34 UTC, ruwanta commented on components/auth/org.wso2.carbon.auth.scim.rest.api/pom.xml
> +            org.wso2.charon3.core.*; version="${charon.core.import.version}",
Why these private, since it is already on import

2018-01-08 05:38 UTC, ruwanta commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/util/ApiServiceUtils.java
> +public class ApiServiceUtils{
Format ? Class Comment ?

2018-01-08 05:38 UTC, ruwanta commented on components/auth/org.wso2.carbon.auth.scim.rest.api/src/main/java/org/wso2/carbon/auth/scim/rest/api/util/ApiServiceUtils.java
> +    public static Response buildResponse(SCIMResponse scimResponse) {
It is better to move this to abstract Service Impl or something. Having too much utility is not good Java practice.

2018-02-07 02:17 UTC, malinthaprasan commented
Changes are manually merged with https://github.com/wso2/carbon-auth/pull/102 due to conflicts

2018-02-07 02:17 UTC, closed without merging